apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: keystone-py
  name: keystone-py
spec:
  ports:
    - name: http-py
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app.kubernetes.io/name: keystone-py
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: keystone-rs
  name: keystone-rs
spec:
  ports:
    - name: http-rs
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: keystone-rs
